### ISSUE TITLE
browser site down

### ISSUE THREAD

**Issue by egg-sketch** [binary-person/rammerhead#101]
the browser.rammerhead site has been down since at least 3:00 PM EDT, maybe longer. It says it cannot connect to the server. Quick check on isitdownrightnow confirms that it isn’t just me. Is there an ETA on when this will be fixed?

**Comment by egg-sketch** [comment]
open source demo seems to work fine btw

**Comment by binary-person** [comment]
thanks for the notification. should be fixed now
