### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by Confu-yokes** [binary-person/rammerhead#12]
Every-time i go to cloud-flare and type in the site i wanna go to i get a bad gateway screen. 
I wait for to most of the times before i refresh the page but it keeps saying that the thing says its the hosts error but i have no clue what do i do ?

**Comment by binary-person** [comment]
did you bind the address to 0.0.0.0 in `config.js`?

**Comment by Confu-yokes** [comment]
No
