### ISSUE TITLE
web demo says "Sessions must come from the same IP"

### ISSUE THREAD

**Issue by 3kh0** [binary-person/rammerhead#16]
I use this proxy for when I am at school and home, can you please remove the `Sessions must come from the same IP` thing because it is really annoying and causes lots of problems for me.

**Comment by rikkipitt** [comment]
In your `config.js` just set `restrictSessionToIP: false`

**Comment by 3kh0** [comment]
@binary-person please remove the ip restriction from https://demo-opensource.rammerhead.org/

**Comment by schooldev49** [comment]
Literally just git clone https://github.com/binary-person/rammerhead.git , cd rammerhead, npm i, npm run build,  and node src/server.js

**Comment by binary-person** [comment]
> @binary-person please remove the ip restriction from https://demo-opensource.rammerhead.org/

sorry. it is there for security reasons. deploy your own if you wish to remove it
