### ISSUE TITLE
Random Downloads

### ISSUE THREAD

**Issue by SteadyStatus21** [binary-person/rammerhead#17]
Hello,
When I am hosting this on Oracle, when I visit websites, sometimes I will get a random file. I will attach them here. Hopefully you can tell me what I did wrong. 
[https://transfer.sh/CBSywX/gi2y.WUD](https://transfer.sh/CBSywX/gi2y.WUD)
Thanks,
SteadyStatus21

**Comment by binary-person** [comment]
can you reattach? and can you tell the steps to reproduce this issue?
