### ISSUE TITLE
Video player shows "loading error"

### ISSUE THREAD

**Issue by darwapls** [binary-person/rammerhead#19]
Hello Mate, Thanks for sharing this wonderful proxy to the community.

I have set it up on my server for testing. Most of the websites works like charm, except when it comes to adult websites. When I tried accessing websites like, x n x x,  x v i deos, x ham ster etc.. Websites opens fine, but when I try to play any videos, am getting "loading error" on the video player.

Can you please help fix the player, help me understand what would have gone wrong?

**Comment by RuralAnemone** [comment]
😳
