### ISSUE TITLE
Replit Error

### ISSUE THREAD

**Issue by ItsLumine** [binary-person/rammerhead#32]
I tried to launch this is Replit and this is what I got
![Screenshot 2022-10-31 11 56 10 AM](https://user-images.githubusercontent.com/99975813/199064881-54f9421c-ac04-47f6-897e-cec4409cdf8e.png)
Do you know how to fix this

**Comment by 3kh0** [comment]
Duplicate of #14, please close this

**Comment by ItsLumine** [comment]
For real, I don't know what to do

**Comment by ItsLumine** [comment]
So I'm closing it as not planned

**Comment by 3kh0** [comment]
@ItsLumine Replit support is planned, but it is not available right now

**Comment by ItsLumine** [comment]
oh
