### ISSUE TITLE
How to go about having rammerhead running on an express server?

### ISSUE THREAD

**Issue by rsa16** [binary-person/rammerhead#34]
Not an issue, just a legitimate question written by an actual programmer and not 10-year-olds trying to use it for their school. I'm trying to create a sort of hub for proxies. After accomplishing the proxy part by having different proxies run at subdomains and then having them in iframes, I'm now trying to track the URL of each proxy. So, I opened inspect element to see how the closed source version of this does it (or at least get a general idea), and I noticed that you have the UI actually running with the proxy.

So, I realized that instead of having the proxy on subdomains I should probably just have them running on different pages. Like rammerhead at `/rh` and womginx at `/wginx`. 

From there, this question popped up. Is it possible to run rammerhead using express at something like `/rh`? If so, how would I go about doing it?

**Comment by 3kh0** [comment]
> legitimate question written by an actual programmer and not 10-year-olds trying to use it for their school

cap 🧢

**Comment by rsa16** [comment]
At the very least I'm not a 10-year-old trying to use it for their school. I'm a 14-year-old trying to use it for his school. A four-year difference.

Anyways, I found out that I could just proxy each server through a different URL with Nginx and do an iframe like that, but is there any better way? I was hoping to only have a single node server running instead of multiple on a single site through Nginx. As my original question states, is their a way to do so with Express.js?

**Comment by 3kh0** [comment]
Why do you need it for school? Are you just being a skid?

**Comment by rsa16** [comment]
My school forces google to use images that are licensed creative commons. This narrows the search results for images down quite a bit, and you know, I don't really like that. So, I decided to do this.

**Comment by 3kh0** [comment]
Use a alternative to Google then, Searx, swiss cows, there are many options

**Comment by rsa16** [comment]
All alternatives are blocked, but I will close this issue regardless since I have achieved what I asked for in the first place. Thanks for not helping lol.

**Comment by RuralAnemone** [comment]
> Why do you need it for school? Are you just being a skid?

what
