### ISSUE TITLE
get a 404 error everytime I put in any link.

### ISSUE THREAD

**Issue by 2Bored4Ever** [binary-person/rammerhead#38]
https://user-images.githubusercontent.com/119268684/209407826-b7433d50-d81f-463f-9ba8-21a10d723d2d.MOV

I'm using this on my school laptop, so maybe it's blocked? It works fine on my tablet.

**Comment by Sunshine-the-eevee** [comment]
possibly, also never thought schools gave away windows laptops, usually they do chromebooks

**Comment by 2Bored4Ever** [comment]
in fairfax county, they do
and since they block every proxy i used, im just gonna close this up-
only used it to listen to [spotify ](https://www.change.org/p/make-fcps-unblock-spotify)😐
