### ISSUE TITLE
redirects to localhost when it tries to load anything

### ISSUE THREAD

**Issue by patritha** [binary-person/rammerhead#51]
when i load up a session on my site it goes to google but when i type in anything to the search bar, it redirects to localhost.

using a physical pc to host
node 18? (im not home but will edit when i am)
i will give any other info if needed

**Comment by pamkin09** [comment]
On [line 28 in src/config.js](https://github.com/binary-person/rammerhead/blob/87791425e310a598b4b8b5299dfecde19ccf3bcb/src/config.js#L28) you have to set your hostname.

**Comment by patritha** [comment]
it works now thaks
