### ISSUE TITLE
obfuscate the code

### ISSUE THREAD

**Issue by Talhoid** [binary-person/rammerhead#56]
securly has found a new way to detect rammerhead and rammerhead browser links.
the code that blocks it is here
```js
var port = chrome.runtime.connect({
    name: "rproxport"
});
async function onWindowLoad() {
    let t = document.evaluate("//script", document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null),
        e = "",
        n = /\/static\/js\/main\.[0-9a-z]{1,}\.js/i;
    for (let a = 0; a < t.snapshotLength; a++)
        if (t.snapshotItem(a)
            .attributes.length > 0 && null != t.snapshotItem(a)
            .attributes.src && null !== t.snapshotItem(a)
            .attributes.src.value.match(n)) {
            e = t.snapshotItem(a)
                .attributes.src.value;
            break
        } if ("" !== e) {
        let t = await fetch(e),
            n = await t.text();
        ("9c6d270f3803b30049faad6927e9b0cd3c6325b3a00ec8a20303049f386add4b" == await sha256(n) || n.includes("M 21 13 h -8 v 8 h -3 v -8 H 2 v -3 h 8 V 2 h 3 v 8 h 8 Z")) && sendData(window.location.href)
    } else {
        let t = document.evaluate("//input", document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
        for (let e = 0; e < t.snapshotLength; e++)
            if (t.snapshotItem(e)
                .attributes.length > 0 && null != t.snapshotItem(e)
                .getAttribute("placeholder") && "click on 'Create new session ID' or 'Fill in existing session ID' from below" == t.snapshotItem(e)
                .getAttribute("placeholder")) {
                sendData(window.location.href);
                break
            }
    }
}
async function sha256(t) {
    const e = (new TextEncoder)
        .encode(t),
        n = await window.crypto.subtle.digest("SHA-256", e);
    return Array.from(new Uint8Array(n))
        .map(t => t.toString(16)
            .padStart(2, "0"))
        .join("")
}
function sendData(t) {
    port.postMessage({
        action: "rprox",
        data: {
            url: window.location.href
        }
    })
}
function callWindowLoadWithTimeOut() {
    setTimeout(onWindowLoad, 2e3)
}
window.addEventListener ? window.addEventListener("load", callWindowLoadWithTimeOut, !1) : window.attachEvent && window.attachEvent("onload", callWindowLoadWithTimeOut);
```

in `onWindowLoad`, securly checks for all /static/js/main.blahblah.js files and loads each one to check for a string, `M 21 13 h -8 v 8 h -3 v -8 H 2 v -3 h 8 V 2 h 3 v 8 h 8 Z`, or if it matches with this hash `9c6d270f3803b30049faad6927e9b0cd3c6325b3a00ec8a20303049f386add4b`, if any of these are found, the url is submitted and securly will block it, even if it cant communicate with securly servers. also, if no scripts were found it checks for an input with placeholder `click on 'Create new session ID' or 'Fill in existing session ID' from below`, the same one as in rammerhead.

you need to obfuscate all the code, or securly will find out.

**Comment by binary-person** [comment]
thank you for bringing this to my attention. I can't do much for open-source rammerhead projects that have already been deployed since the hosts likely won't update it.

However, I've made some small changes to the rammerhead browser codebase so it should be fine now. Please update me when securly updates to patch my updates

**Comment by Teerths** [comment]
nice!

**Comment by Talhoid** [comment]
> thank you for bringing this to my attention. I can't do much for open-source rammerhead projects that have already been deployed since the hosts likely won't update it.
> 
> However, I've made some small changes to the rammerhead browser codebase so it should be fine now. Please update me when securly updates to patch my updates

didnt notice you sent this, thanks
