### ISSUE TITLE
QUESTION?

### ISSUE THREAD

**Issue by Karichain** [binary-person/rammerhead#58]
Can somebody just make a google doc or something with a bunch of rammerhead links because i am so done on trying to find them i spend more time trying to find them then playing football

**Comment by RuralAnemone** [comment]
join the discord, they're all in there

**Comment by Karichain** [comment]
i need a rammerhead to go on discord

**Comment by Karichain** [comment]
blocked

**Comment by binary-person** [comment]
links in discord
