### ISSUE TITLE
Issue with deployment to replit.

### ISSUE THREAD

**Issue by Notplayingallday383** [binary-person/rammerhead#67]
Hi, Recently I have deployed rammerhead to replit and set it up the say it said so in README.md but I encountered an issue that there is no web ui and the local host port doesn't work. There are versions of rammerhead already on replit but they are all older  versions. 
![image](https://github.com/binary-person/rammerhead/assets/72810050/caa8763f-bbb5-4b96-bd94-ac1354301851)

**Comment by ltong4867** [comment]
When deploying on Replit, make sure to change your port in config.js to 0.0.0.0.
Ignore the Run this Repl to see the hosted output. Then, go to [replname].[yourusername].repl.co. You should see your Rammerhead instance being displayed properly.
