### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by OmzBD** [binary-person/rammerhead#72]
It loads, but when I search for something it doesn't load at all. Can you fix it please?

**Comment by binary-person** [comment]
The old IP address just got yanked yesterday. I have already notified everyone about it in the discord. If you’re the owner, you can find more information in the discord server announcements

**Comment by binary-person** [comment]
never mind, it looks like the server doesn't have connectivity. i'll try to restore it within a couple of days

**Comment by binary-person** [comment]
it's back now

**Comment by OmzBD** [comment]
Thank you very much
