### ISSUE TITLE
hCaptcha not working

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [binary-person/rammerhead#8]
hCaptcha works on the private server, however the public rammerhead source does not work.
https://canary.discord.com/channels/886630771182407731/886632637370888242/958045730285711400

**Comment by binary-person** [comment]
public demo works?

**Comment by FoxNerdSaysMoo** [comment]
Yes, public demo works

**Comment by kcar06** [comment]
Rammerhead has CAPTCHA disabled, it is a demo.

**Comment by binary-person** [comment]
please reopen if issue still persists, whether it's on your local machine or on the demo version
