### ISSUE TITLE
rammerhead.github.io 404 Not Found

### ISSUE THREAD

**Issue by burnsboyamazing** [binary-person/rammerhead#91]
On a school Chromebook, it gets "404 Not Found".
[Screen recording 2024-01-09 1.49.51 PM.webm](https://github.com/binary-person/rammerhead/assets/154830140/aca93684-e30b-4cf1-967a-2aff0dfc8816)
I tried on a hp Chromebook, still "404 Not Found" error in school Chromebook.
[Screen recording 2024-01-09 3.09.59 PM.webm](https://github.com/binary-person/rammerhead/assets/154830140/0390c11b-89d0-45b3-9766-fd67a20574c1)
@binary-person Still "404 Not Found" in rammerhead.github.io.
In downdetector.ca/status/github, at 9 AM it's growing down then up on me. But still getting "404 Not Found" when going to rammerhead.github.io.
![Screenshot 2024-01-09 3 11 13 PM](https://github.com/binary-person/rammerhead/assets/154830140/2452fae3-fbec-4c37-b9ab-5d10ec9eb27f)
@e9x Still getting the error in rammerhead.github.io.

**Comment by binary-person** [comment]
the github is only for sharing the code. the links are in the discord in the readme, and the demo links on the readme of this page
